name: Complete Workflow

on:
  push:
    paths:
      - '**/*.*'
  pull_request:
    paths:
      - '**/*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          
      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        
      - name: Run psalm
        run: ./vendor/bin/psalm --shepherd --threads=2 --no-cache --output-format=github

      - name: Run Tests
        run: |
          php vendor/bin/phpunit --coverage-clover coverage.xml --configuration phpunit.xml tests
      
      - name: Convert Clover to Cobertura
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx clover-to-cobertura ./coverage.xml > ./coverage-cobertura.xml

      - uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./coverage-cobertura.xml
    
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage.xml
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: src/,demos/,tests/
          output: text
          ruleset: phpmd.xml
